### ISSUE TITLE
Confirms it imports "Notes" from Gmail but nothing in Google Keep

### ISSUE THREAD

**Issue by eadickey** [lambrospetrou/gmail-keep-importer#17] opened 2019-05-06 13:57 UTC
Confirms it imports multiple "Notes" from Gmail but nothing in Google Keep.  Am on the home page and have signed out of Keep and back in.  I tried searching for the notes but couldn't find.

**Comment by lambrospetrou** [comment] 2019-05-06 15:42
Duplicate of https://github.com/lambrospetrou/gmail-keep-importer/issues/16

**Closed by lambrospetrou** 2019-05-06 15:42 UTC
